### ISSUE TITLE
Use SOWFA to generate an inflow and give it to FAST.Farm?

### ISSUE THREAD

**Issue by pingha** [OpenFAST/openfast#1528]
Dear Jason Jonkman, I now want to use SOWFA to generate an inflow and give it to FAST.Farm. May I know how to proceed? I see an example called LESinflow in FAST.Farm

**Comment by jjonkman** [comment]
Dear @pingha,

Please see the FAST.Farm modeling guidance for inflow wind generation from high-fidelity precursor simulations: https://openfast.readthedocs.io/en/main/source/user/fast.farm/ModelGuidance.html#inflow-wind-generation.  That said, these days, we more frequently use AMR-Wind than SOWFA for high-fidelity precursor simulations for FAST.Farm: https://github.com/Exawind/amr-wind.

If you are not already aware, there have been quite a few improvements recently to the python scrips that support FAST.Farm, see: https://github.com/OpenFAST/python-toolbox.

Best regards

**Comment by pingha** [comment]
Hi, Dear @jjonkman
I have another question to ask you. I have read your article titled "A model to calculate fatigue damage caused by partial washing during wind farm optimization". Therefore, I used FAST.Farm to study the bending moment at the root of a fan blade under different wind speeds. I used Turbosim to generate inflow, and generated wind speeds of 3m/s-25m/s to see the bending moment in the flapwise and edgewise directions at the root, But every time my wind speed reaches a certain level, the obtained bending moment will undergo a sudden change, and the trend of the bending moment change in the edgewise direction is also different from the trend in your paper graph. Do you know why? In addition, I saw that the azimuth written above the graph in your paper is 90 °. Does 90 ° here refer to the direction of the wind? Or does it refer to the angle of the turbine blades? If it is the angle of the turbine blade, I have a question. The angle of the turbine blade should constantly change during turbine operation. Why can you fix the angle of the turbine blade here? Regarding Figure 4 in your paper, I do not understand these. I have placed the relevant images below and look forward to your reply.

![QFHV~75JP`~X48{OZ7EM$11](https://user-images.githubusercontent.com/108447902/232652551-fa26a3fe-64d6-4895-921c-3ae3d3f15b3f.png)
![1](https://user-images.githubusercontent.com/108447902/232653513-d6402e67-9991-4b9d-aea4-01d581571d4e.png)
![2](https://user-images.githubusercontent.com/108447902/232653562-485af9a9-2b93-49d6-9e8b-20bf2e66e61e.png)
![3](https://user-images.githubusercontent.com/108447902/232653586-6dfbb89e-9765-480b-b326-afb33e97171e.png)

**Comment by jjonkman** [comment]
Dear @pingha,

I was not a couthor of the paper you reference, but here are my responses:
- I'm not sure what is causing your flapwise and edgewise loads to change at 19, 20, and 22 m/s.  Can you clarify how you are generating these figures?  (Are you plotting the time-series mean load from time-series simulations?)  Do other responses such as rotor speed and blade pitch look correct?
- Figure 4 shows the effect of the rotor blade azimuth angle.
 
Best regards,

**Comment by pingha** [comment]
Hi, Dear @jjonkman
I'm very sorry to overlook that you are not the author of this paper. I have read many NREL papers before, and the authors in them all include you. This has caused me to think of you as soon as I saw NREL. I apologize again.
In addition, for my two images, I used turbosim to generate different wind speeds. I changed the URef in "90m_08mps. inp" in the TSinflow example under FAST.Farm, and changed RefHt to the actual hub height of 90m. Then, I simulated the wind speed from 3m/s to 25m/s. After obtaining the turbine response, I simulated for 660s and selected the maximum value from the last 100s for plotting.
Through your reminder, I found that under the three sudden changes in wind speed, the rotor speed and blade pitch angle also became abnormal. At present, I have not found the reason. I am using an NREL-5MW turbine.
You said that Figure 4 shows the influence of blade azimuth angle. I would like to know the approximate process of this simulation? I feel that I don't quite understand Figure 4. During the simulation process, the blade azimuth angle of the fan does not always change, but from Figure 4, it can be seen that the blade azimuth angle is always a fixed value. It is simulated under different wind speeds, and then the load response at a blade azimuth angle of 90 degrees is selected each time? I have tried this before, but after outputting the results, I found that the same blade may have experienced more than one blade azimuth angle of 90 ° during the simulation process. Finally, what do you mean by "blade pitch" is the pitch angle of the blade? Is this the meaning of Figure 3 in the paper? I also placed Figure 3 in the paper below.
Below are some of my graphs. There is no problem at 18m/s wind speed, but there will be problems at 19m/s. At first, I thought it was caused by excessive wind speed, but looking at the trend of the graph, the wind speed later was higher, and some did not have problems. Looking forward to your reply.
![1](https://user-images.githubusercontent.com/108447902/232945782-0aa83ecd-5aa0-41a4-a22c-fc9a4cdf5558.png)
![2](https://user-images.githubusercontent.com/108447902/232945878-01b21ef1-9130-495b-9ef6-6a5baf345e7a.png)
![3](https://user-images.githubusercontent.com/108447902/232945889-28448100-9d26-443a-8914-58f3eb657b75.png)
![4](https://user-images.githubusercontent.com/108447902/232945911-ab720a1f-69c8-4716-9871-2bbbad815c63.png)
![5](https://user-images.githubusercontent.com/108447902/232945928-b318fca1-4e0c-4996-a06d-cd6010ff7fc7.png)
![6](https://user-images.githubusercontent.com/108447902/232945939-a61349db-0187-4f7d-bc71-98aa723a6346.png)

**Comment by pingha** [comment]
Dear @jjonkman 

Thank you for your answer. As you mentioned, I set the initial blade pitch angle and speed for the fan before each operation. After simulating again, there were no previous problems. Here, I would like to ask that in previous simulations, I did not set the corresponding initial speed and blade pitch angle, but this problem did not occur in subsequent simulations. I believe that the controller is working, So in the 19,20 and 22m/s simulations, the initial values were not set, and it was an error that made me realize this. Do you mean that regardless of the wind speed, I should set the relevant initial values before each simulation?

In addition, I currently want to conduct some research on wind turbine fatigue, and for this reason, I need to conduct a lot of simulations. I am currently using FAST.Farm for simulation, which is very fast in calculating the response of the wind turbine. However, every time I use turbosim to generate the wind field, this process takes me several hours. I think doing so and conducting a large number of simulations is too time-consuming, May I ask if you have any other methods for quickly generating inflow wind farms? This way, I can shorten the time spent on simulation.

**Comment by jjonkman** [comment]
Dear @pingha,

> Do you mean that regardless of the wind speed, I should set the relevant initial values before each simulation?

Yes, this is a generally recommended practice as has been discussed many times on this issues page and on our forum.  Using incorrect initial conditions may result in the controller not being able to recover and producing unphysical results.

Generating farm-wide turbulent inflow for FAST.Farm can be time consuming.  For small wind farms, TurbSim likely suffices, but for large wind farms, a high-fidelity precursor simulation (from AMR-Wind or SOWFA) is likely required.  When using TurbSim to generate wind inflow for FAST.Farm, the `Mod_AmbWind` = 3 approach of FAST.Farm is generally more efficient because it always you to tailor separate TurbSim wind data files for the low-resolution (coarse discretization) and high-resolution (fine discretization) domains.   When generating wind inflow for use in FAST.Farm, I would recommend following the modeling guidance (https://openfast.readthedocs.io/en/main/source/user/fast.farm/ModelGuidance.html) and using the python toolbox, including recent updates that make the process much easier (https://github.com/OpenFAST/python-toolbox/pull/56).

Best regards,

**Comment by pingha** [comment]
Dear @jjonkman

Thank you for your suggestion. Currently, I plan to use FAST.Farm to study the fatigue load of two wind turbines. This should belong to the category of small wind farms, and I apologize for not being specific enough before. I would like to ask for your advice. If I only study two wind turbines, which parameters do I need to change to design different simulation scenarios regarding fatigue? Do you have any suggestions in this regard? Because I currently think the spacing between turbines is also a variable, I did not design the wind farm size too small in the. fstf main file of FAST.Farm, which also caused me to generate inflow slowly using the. inp file.

In addition, I would like to ask you another question. If I were to use an. inp file to generate an inflow and need to change the wind direction, which specific parameters should be changed? I saw two parameters in the. inp file and the inflowWind.dat file, and I am not very sure if the two parameters that are very similar in these two files mean the same thing. After reading the turbsim manual, I still don't quite understand. I tried the following situation: 
case1. After changing the VFlowAng in the. inp file to 0 and HFlowAng to 10, I found that the wind direction did indeed change; 
case2. The VFlowAng and HFlowAng in the .inp file are set to 0. If the PropagationDir in the inflowWind.dat file is changed to 10, an error will occur during operation. I have placed the relevant figures below and look forward to your reply.
![1](https://user-images.githubusercontent.com/108447902/233654211-cb228a97-01d3-4f76-bf01-5e817b0e9334.png)


![2](https://user-images.githubusercontent.com/108447902/233654222-d9d2b72c-4ef6-4990-b45c-17ff2694e50d.png)
![3](https://user-images.githubusercontent.com/108447902/233654234-4fbece34-a5a7-4e67-b5a4-b0c04e1047ff.png)
![4](https://user-images.githubusercontent.com/108447902/233654251-21f39b44-a026-4cad-996c-84d493a50d6f.png)

**Comment by jjonkman** [comment]
Dear @pingha,

Fatigue loads during normal operation are typically found by running a series of simulations from cut-in to cut-out wind speed, e.g., using 2-m/s bins from 3 to 25 m/s and 6 turbulence seeds per bin, would be 66 simulations for a given turbulence level.

It is generally not recommend to set `HFlowAng` nonzero in in TurbSim when using TurbSim wind data within InflowWind due to the use of Taylor's frozen turbulence assumption in InflowWind.

In standalone OpenFAST (uncoupled from FAST.Farm), we generally recommend setting `PropagationDir` in InflowWind to change the wind direction.  

However, the FAST.Farm modeling guidance recommends keeping `PropagationDir` in InflowWind set to zero, which is why the FAST.Farm modeling guidance recommends rotating the wind farm rather than changing the wind direction when using TurbSim-based inflow in FAST.Farm.

Best regards,

**Comment by pingha** [comment]
Dear @jjonkman

At present, I want to use FAST. Farm to study the fatigue load of two turbines. I want to change some parameters to set up multiple simulation situations, such as turbulence intensity and wind speed. I want to get a turbine response database, and then use neural network and other methods to train a surrogate model. I want to ask you what other parameters I need to consider in terms of parameter selection besides turbulence intensity and wind speed, Currently, due to limitations in time and computing resources, I cannot consider it comprehensively because there are too many parameters that have changed and too many simulations have been conducted, which I am unable to achieve on my end. Looking forward to your reply.

**Comment by pingha** [comment]
Dear @jjonkman

Thank you for your previous reply. I have another question to ask you. I conducted a comparison of two calculation examples, one using SWOFA and the other using FAST. Farm. The inflow wind speed at the hub height is 8m/s and the turbulence intensity is 5.6%. Three turbines were calculated, including the first one. I turned off its yaw freedom and set the initial yaw angle to 15 degrees. After comparison, I found that:, The power calculated by FAST. Farm is always slightly lower than that calculated by SOWFA. May I ask if there are any issues with FAST. Farm in considering turbine yaw calculations? I will put the relevant pictures and some settings in the calculation examples below, and look forward to your reply.

![1](https://user-images.githubusercontent.com/108447902/234235659-ecef11a8-c61f-4e22-918b-6d84bd95616d.jpg)
![2](https://user-images.githubusercontent.com/108447902/234235663-b128f069-c1a8-461e-9529-78878d91cf79.png)
![3](https://user-images.githubusercontent.com/108447902/234235666-0e6d79f4-d28b-4b52-b082-52a400570cc8.png)
![4](https://user-images.githubusercontent.com/108447902/234235680-da511ad4-3452-4ff5-950a-3e4bad6d9967.png)
![5](https://user-images.githubusercontent.com/108447902/234235690-69465195-b665-44d7-b889-ecfbee4d9e8b.png)
![6](https://user-images.githubusercontent.com/108447902/234235693-97dbda07-7f36-459a-ab86-a55540f6adf1.png)
![7](https://user-images.githubusercontent.com/108447902/234235696-6e8ba824-fdf3-4880-b377-4f0bc28e6de6.png)
![8](https://user-images.githubusercontent.com/108447902/234235700-681d9f18-8370-48e1-80c7-cd5f65c21bdf.png)
![9](https://user-images.githubusercontent.com/108447902/234235718-028fad65-e78e-4263-9123-72d594da86c4.png)
![10](https://user-images.githubusercontent.com/108447902/234235734-f89e07f2-ea1f-4607-97e0-efe2425a0a74.png)
![1](https://user-images.githubusercontent.com/108447902/234237810-9c1a8432-8722-4cb3-88a7-d5e5d00d31f9.png)
![2](https://user-images.githubusercontent.com/108447902/234237818-da9d5fb3-a7cd-486e-8d04-0f7da339bd6c.png)
![3](https://user-images.githubusercontent.com/108447902/234237820-9387feca-1a2a-439e-89ed-a660dc57e7be.png)

**Comment by jjonkman** [comment]
Dear @pingha,

Regarding your first question, the following NREL publications are likely of interest to you--related to the use of FAST.Farm to generate surrogate models for the loading of downstream wind turbines:
https://www.nrel.gov/docs/fy22osti/78861.pdf
https://www.nrel.gov/docs/fy22osti/82524.pdf

(Please note that I'm not a coauthor on these papers, so, can't speak to their details.)

Regarding your second question, I think we've recently realized that the original polar wake model of FAST.Farm can overpredict wake deflection in skewed flow.  Collaboration of the wake-related parameters, such as the wake deflection correction parameters can help.  We've also recently released the new curled wake model into FAST.Farm that is aimed at improving the prediction of wakes under skewed flow: https://www.nrel.gov/docs/fy23osti/82963.pdf.  Comparisons between FAST.Farm and SOWFA for wake steering applications have also been discussed on our forum: https://forums.nrel.gov/t/fast-farm/1887.  Otherwise, I'm not fully sure I understand the results you are sharing regarding power.

I also notice that your turbulence intensity is low, where FAST.Farm is known to underpredict wake-induced turbulence.  NREL is working to resolve that by introducing a new wake-added turbulence model into FAST.Farm.

Best regards,

**Comment by jjonkman** [comment]
Dear @pingha,

Here are my responses:

- To change the location of a wind turbine in FAST.Farm, I would expect that you'd have to change `WT_X`, `WT_Y`, `WT_Z` and `X0_High`, `Y0_High`, and `Z0_High` in FAST.Farm.  And the FAST.Farm modeling guidance would recommend that when changing `X0_High`, `Y0_High`, and `Z0_High`, that you also change the inflow set up in TurbSim so that the low- and high-resolution domains of FAST.Farm are aligned with the TurbSim grid. 
- I agree that the TSinflow example of FAST.Farm does not strictly follow the modeling guidance.  This is because the model was selected as sufficient for testing purposes with reduced memory requirements, not to be an example for best practices for users to follow.
- In general, we recommend to following the FAST.Farm modeling guidance as documented.  For inflow generation and FAST.Farm model setup, we also recommend that you use the python scrips that support FAST.Farm--which naturally follow the modeling guidance--see: https://github.com/OpenFAST/python-toolbox.

Best regards,

**Comment by pingha** [comment]
Dear @jjonkman

Thank you for your reply. I may not have clearly described it in the message just now. I am currently conducting the simulation of two turbines in FAST.Farm. If I don't want to change the inflow conditions, I just want to change the position of the second turbine. Can I do it in the following way? My approach is to keep the position of the first turbine in the upstream, move the position of the second turbine, and modify the relevant parameters of the second turbine directly in the Tsinflow.fstf file directly after Turbsim generates the flow wind field. I consider doing so because It takes a few hours for TurSIm to generate inflow, and I don't change the inflow conditions, so I want to do this to save time. Looking forward to your reply.

**Comment by pingha** [comment]
Dear @jjonkman

When I was using FAST.Farm simulation, there was a problem. I set the inflow wind speed at the hub height to 24m/s, the turbulence intensity was 20%, and 660s. I outputted the time after 600s. I found that there was a problem with the output speed, and the average speed was only 2.336r. Pm, sometimes the rotation speed is even negative. In the last period of time, the rotation speed is only 1.478 rpm. There is also a problem with the fluctuation of the paddle distance angle of the turbine blade. There is a big gap between these two parameters and the values on the NREL-5MW turbine manual. I want to ask if you know the reason? Or can't FAST.Farm itself calculate such a large wind speed and turbulence?

I will put the relevant pictures below and look forward to your reply.

![1](https://user-images.githubusercontent.com/108447902/236724208-d08a7362-8882-4317-acde-77b77aa549f4.png)
![2](https://user-images.githubusercontent.com/108447902/236724216-9de0c747-4791-460a-8194-abf07a9364e4.png)


![3](https://user-images.githubusercontent.com/108447902/236724222-cf397400-81a4-4a55-a4fd-1402158f6304.png)
![4](https://user-images.githubusercontent.com/108447902/236724233-48b04133-1fa0-442b-af78-1685df5f0a71.png)
![5](https://user-images.githubusercontent.com/108447902/236724240-005c2fa3-d6f1-40f1-94d9-a3fac7f4a1c9.jpg)

**Comment by jjonkman** [comment]
Dear @pingha,

It looks like the controller response is unstable because of the use of improper initial conditions.  As has been discussed many times on OpenFAST issues and our forum, you must set proper initial conditions to ensure that the controller functions properly.  In general, it is recommend to set the initial rotor speed and initial blade-pitch angle to their expected (mean) values for the mean hub-height wind speed you are simulating.  At 24 m/s for the NREL 5-MW baseline wind turbine, this would be `RotSpeed` = 12 rpm (which you have set) and `BlPitch` = 22.35deg; setting that should resolve the issue.

Best regards,

**Comment by pingha** [comment]
Dear @jjonkman
Sorry, maybe I didn't make it clear just now. I had a similar problem before, so I have set the initial speed and blade pitch angle before each simulation. As you said, I have set the initial speed and blade pitch angle ( RotSpeed= 12 rpm ,BlPitch(1) = 22.35deg、BlPitch(2) = 22.35deg、BlPitch(3) = 22.35deg)before the simulation, but such an error still occurred. Do you know the possible reason?

**Comment by pingha** [comment]
Dear @jjonkman

Sorry, I'm not sure where to find the initial blade pitch angle under different wind speeds. Do you mean that at a wind speed of 24m/s, the initial blade pitch angle is not 22.35 degrees, but in your recent reply, it is indeed 22.35 degrees. I don't quite understand what you mean?
Looking forward to your reply.

**Comment by jjonkman** [comment]
Dear @jjonkman.

Looking at your post above where you shared your ElastoDyn input file, I now see that the initial conditions are set correctly for 24 m/s.  Did you edit the post to correct this, or did I just misread your original post?

Best regards,

**Comment by pingha** [comment]
Dear @jjonkman

I set it up before the simulation, I have set the initial speed and blade pitch angle ( RotSpeed= 12 rpm ,BlPitch(1) = 22.35deg、BlPitch(2) = 22.35deg、BlPitch(3) = 22.35deg)before the simulation, but such an error still occurred. The controller seems to be out of function, and the output pitch angle and rotation speed seem to be wrong. Do you know where it is wrong? In the picture above, I also have one of the error prompts.

**Comment by jjonkman** [comment]
Dear @jjonkman,

Can you share the time series of RotSpeed and BlPitch from time zero until the problem arises?  Does the unstable behavior start at time zero or later into the simulation?

Best regards,

**Comment by jjonkman** [comment]
Dear @pingha,

It appears that your controller is not behaving properly.  Can you rerun the simulation outputting everything from time zero?  Also, can you share your full output file a different way (e.g., a link to Google drive)?

Best regards,

**Comment by pingha** [comment]
[Uploading WT2.xlsx…]()

**Comment by jjonkman** [comment]
Dear @pingha,

The controller seems to behave as expected until about 165 s into the simulation, at which point the controller goes unstable.  It is unclear to me what is causing this.  Are there other outputs from OpenFAST or FAST.Farm that are changing (such as a large change in wind speed) just before this time that would give a clue as to why the controller is not behaving properly?  I was expecting that may have been when the wake of the upstream turbine first hits the downstream turbine, but given your 24 m/s wind speed and short 370 m spacing, the wake would from the upstream turbine would hit the downstream turbine much sooner than 165 s.  It may help to plot a horizontal visualization of the flow at hub height from FAST.Farm to see if there is any anomalies in the flow around this time.

Best regards,

**Comment by pingha** [comment]
Dear @jjonkman,
Thank you for your suggestion. I will output the wind speed visualization file of the whole wind field to check and see if I can find the problem.

In addition, during this period, I want to study the optimization of the turbine layout of the wind farm considering the fatigue load of the turbine. At present, I have carried out some simulations for the two turbines, but combined with the subsequent wind farm layout optimization, I suddenly have some questions. I plan to conduct a large number of working condition simulations, and then extract the inflow wind speed, turbulence intensity, turbine spacing, wind shear index, etc. as the model input of machine learning, and then use some equivalent fatigue loads of the response as the output, so as to facilitate the rapid prediction of fatigue in the future optimization. But I suddenly found that it seemed meaningless for me to simulate two turbines, and it seemed to be enough to simulate only one turbine. Because in the optimization of the wind farm, I should use the wake model to calculate the fan in different positions, so I should only simulate the equivalent fatigue load of a fan under different wind speeds, turbulence intensity, etc. I think that in the wind farm of multiple turbines, even if the positions of these turbines are different and the turbulence intensity is different, some of the final factors are attributed to the inflow wind speed of the turbine, and the simulation of different wind conditions with one turbine can already get the required results. I only need to be in the process of wind farm optimization. Calculate the real inlet wind speed of different turbines and bring it into the model prediction of the equivalent fatigue load of my single turbine. Using the simulation of two turbines, in fact, I don't know what the real inlet wind speed of the downstream turbine is. If I extract the wind speed of the downstream turbine, it will be a relatively large workload. I don't know if my idea is correct? I hope you can give me some suggestions for my work.

Looking forward to your reply.

**Comment by jjonkman** [comment]
Dear @pingha,

I think the challenge is that the characteristics of the waked inflow may differ from the characteristics of ambient inflow.  You mention wind speed, TI, shear, etc, but there are other inflow characteristics such as length scale, Reynolds stresses, localized shear in waked inflow, etc.

The following papers (not mine) are likely of interest to you:
https://www.nrel.gov/docs/fy22osti/78861.pdf
https://www.nrel.gov/docs/fy22osti/82524.pdf

Best regards,

**Comment by pingha** [comment]
Dear @jjonkman,
At present, I have calculated some simulations. Now I want to use Mlife to calculate some equivalent fatigue loads of load responses. In using Mlife, I don't know the Lult of several load responses I calculated. I use NREL-5WM turbines, which I didn't find in Mlife's manual. About Lult in various parts of this turbine. I also want to ask if I just want to get the equivalent fatigue load, do I need to use Lult?

In addition, I also want to ask about TypeLMF. At present, I use FAST.Farm to calculate the response of some turbines. I just got some load schedule data. I don't know the fixed average load of each load, so I should choose WM or AM?
Looking forward to your reply.

![AA5069B4567878DDCE9CA37AC938D516](https://github.com/OpenFAST/openfast/assets/108447902/ab466067-9f79-4838-aa34-5e023a4c61fc)

**Comment by pingha** [comment]
Dear @jjonkman,

I would like to ask you if you have the thrust coefficient curve of the NREL-5MW wind turbine, the curve of the thrust coefficient of the wind turbine as a function of wind speed, I did not find it in the NREL-5MW wind turbine brochure.

Looking forward to your reply.

**Comment by jjonkman** [comment]
Dear @pingha,

Is this what you are looking for: https://forums.nrel.gov/t/nrel-5-mw-reference-turbine-cp-cq-ct-coefficients/456?

Best regards,

**Comment by SYZ622** [comment]
@pingha Hello! I would like to ask how you drew this wake diagram. Why don't my diagrams have this effect?

Looking forward to your reply, thank you!

![Image](https://github.com/user-attachments/assets/7c2a5546-38c0-4189-aff8-53c961227a15)

![Image](https://github.com/user-attachments/assets/b93bd7dd-5557-4a83-a23e-dceb8e484bfa)
